"""
Generate union DDL from ecjoy PG schema (read-only introspection).

Why: pg_dump 16 cannot dump a PG 17 server. We introspect information_schema
and emit CREATE TABLE statements for ALL ecjoy public tables, then add the
priya-only column `style` to `characters` so target = union(ecjoy, priya).

Output: priya_union_schema.sql (review before applying).
Usage: python gen_union_ddl.py
"""
import os

import psycopg2
import psycopg2.extras

ECJOY_URL = os.getenv(
    "ECJOY_DATABASE_URL",
    "postgresql://postgres:YRQ21163x%21ecjoy@db.agnithttoxexijxkksbv.supabase.co:5432/postgres",
)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "priya_union_schema.sql")

# priya-only columns to add on top of ecjoy structure (table_name -> list of
# (name, type, nullable, default)). This realizes the union of columns.
EXTRA_COLUMNS = {
    "characters": [("style", "varchar", "YES", None)],
}


def col_type_sql(c):
    dt = c["data_type"]
    udt = c["udt_name"]
    maxlen = c["character_maximum_length"]
    if dt == "character varying":
        return f"varchar({maxlen})" if maxlen else "varchar"
    if dt == "character":
        return f"char({maxlen})" if maxlen else "char"
    if dt == "numeric":
        p, s = c.get("numeric_precision"), c.get("numeric_scale")
        return f"numeric({p},{s})" if p is not None else "numeric"
    if dt == "USER-DEFINED":
        return udt
    if dt == "ARRAY":
        return udt.lstrip("_") + "[]"
    return dt


def render_column(c):
    name = c["column_name"]
    typ = col_type_sql(c)
    default = c["column_default"]
    nullable = c["is_nullable"] == "YES"
    is_serial = default is not None and default.startswith("nextval(")
    if is_serial:
        base = "bigint" if typ == "bigint" else "integer"
        return f'"{name}" {base} GENERATED BY DEFAULT AS IDENTITY'
    parts = [f'"{name}"', typ]
    if default is not None:
        parts.append(f"DEFAULT {default}")
    if not nullable:
        parts.append("NOT NULL")
    return " ".join(parts)


def main():
    conn = psycopg2.connect(ECJOY_URL, connect_timeout=20)
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    cur.execute(
        """
        SELECT table_name, column_name, data_type, udt_name, is_nullable,
               column_default, character_maximum_length,
               numeric_precision, numeric_scale, ordinal_position
        FROM information_schema.columns
        WHERE table_schema='public'
        ORDER BY table_name, ordinal_position
        """
    )
    cols = {}
    for r in cur.fetchall():
        cols.setdefault(r["table_name"], []).append(dict(r))

    cur.execute(
        """
        SELECT tc.table_name, kcu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name=kcu.constraint_name
         AND tc.table_schema=kcu.table_schema
        WHERE tc.constraint_type='PRIMARY KEY' AND tc.table_schema='public'
        ORDER BY tc.table_name, kcu.ordinal_position
        """
    )
    pks = {}
    for r in cur.fetchall():
        pks.setdefault(r["table_name"], []).append(r["column_name"])
    conn.close()

    lines = [
        "-- Union schema for priya Supabase = ecjoy public tables + priya-only columns.",
        "-- Generated by gen_union_ddl.py (read-only introspection of ecjoy).",
        "-- Re-runnable: CREATE TABLE IF NOT EXISTS.",
        "",
    ]
    for t in sorted(cols.keys()):
        coldefs = [render_column(c) for c in cols[t]]
        for (cn, ct, nul, df) in EXTRA_COLUMNS.get(t, []):
            extra = f'"{cn}" {ct}'
            if df is not None:
                extra += f" DEFAULT {df}"
            if nul == "NO":
                extra += " NOT NULL"
            coldefs.append(extra)
        if pks.get(t):
            pk_cols = ", ".join(f'"{c}"' for c in pks[t])
            coldefs.append(f"PRIMARY KEY ({pk_cols})")
        body = ",\n  ".join(coldefs)
        lines.append(f'CREATE TABLE IF NOT EXISTS "{t}" (\n  {body}\n);')
        lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {OUT} ({len(cols)} tables)")


if __name__ == "__main__":
    main()
