-- Union schema for priya Supabase = ecjoy public tables + priya-only columns.
-- Generated by gen_union_ddl.py (read-only introspection of ecjoy).
-- Re-runnable: CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS "access_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "ip" varchar NOT NULL,
  "country" varchar,
  "country_code" varchar,
  "city" varchar,
  "lat" double precision,
  "lon" double precision,
  "path" varchar NOT NULL,
  "method" varchar NOT NULL,
  "user_id" varchar,
  "user_email" varchar,
  "status_code" integer,
  "response_time_ms" double precision,
  "timestamp" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "account_appeals" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "reason" text NOT NULL,
  "contact" varchar,
  "status" varchar DEFAULT '''pending'''::character varying,
  "admin_reply" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ad_clicks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "source" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ad_impressions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "source" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "agent_profiles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "tier" varchar,
  "commission_rate" double precision,
  "total_commission_points" integer,
  "total_invited_paid_users" integer,
  "is_kol" boolean,
  "kol_verified_at" timestamp without time zone,
  "kol_platform" varchar,
  "kol_follower_count" integer,
  "created_at" timestamp without time zone DEFAULT now(),
  "updated_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "api_call_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "service" varchar NOT NULL,
  "model" varchar NOT NULL,
  "provider" varchar NOT NULL,
  "input_tokens" integer,
  "output_tokens" integer,
  "character_name" varchar,
  "status" varchar NOT NULL,
  "error_message" text,
  "duration_ms" double precision,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "billing_config" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "service_key" varchar,
  "cost" integer,
  "label" varchar,
  "updated_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "casbin_rule" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "ptype" varchar(255),
  "v0" varchar(255),
  "v1" varchar(255),
  "v2" varchar(255),
  "v3" varchar(255),
  "v4" varchar(255),
  "v5" varchar(255),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "character_attribute_options" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "gender" varchar NOT NULL,
  "style" varchar NOT NULL,
  "category" varchar NOT NULL,
  "option_id" varchar NOT NULL,
  "label" varchar NOT NULL,
  "image_url" varchar NOT NULL,
  "sort_order" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "character_follows" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "character_id" integer NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "character_media" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "character_id" integer NOT NULL,
  "type" text DEFAULT 'image'::text NOT NULL,
  "url" text NOT NULL,
  "media_status" varchar(20) DEFAULT 'pending'::character varying,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "character_reference_images" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "character_id" integer NOT NULL,
  "vfe_frame_id" integer,
  "image_url" text NOT NULL,
  "prompt" text,
  "dimensions" jsonb DEFAULT '{}'::jsonb,
  "tags" jsonb DEFAULT '[]'::jsonb,
  "style" text,
  "description" text,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "character_swapface_images" (
  "character_id" integer NOT NULL,
  "result_file_path" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  PRIMARY KEY ("character_id", "result_file_path")
);

CREATE TABLE IF NOT EXISTS "characters" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar,
  "url" varchar,
  "description" text,
  "attributes" json,
  "media" json,
  "voice_id" varchar,
  "creator_id" varchar,
  "category" varchar,
  "tags" json,
  "chat_model" varchar,
  "output_language" varchar,
  "intimacy_difficulty" varchar,
  "sort_priority" integer,
  "is_deleted" boolean,
  "deleted_at" timestamp without time zone,
  "deleted_by" varchar,
  "is_shared" boolean,
  "shared_at" timestamp without time zone,
  "content_rating" varchar DEFAULT 'sfw'::character varying,
  "character_status" varchar(20) DEFAULT 'pending'::character varying,
  "style" varchar,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "chat_history" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "character_name" varchar,
  "role" varchar,
  "content" text,
  "media_url" varchar,
  "media_type" varchar,
  "timestamp" timestamp with time zone DEFAULT now(),
  "is_read" boolean,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "commission_records" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "agent_user_id" varchar,
  "source_user_id" varchar,
  "payment_amount" integer,
  "commission_rate" double precision,
  "commission_points" integer,
  "payment_reference_id" varchar,
  "status" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "daily_stats" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "date" varchar NOT NULL,
  "pv" integer,
  "uv" integer,
  "new_users" integer,
  "total_users" integer,
  "api_calls" integer,
  "updated_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "daily_temptations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "date" varchar NOT NULL,
  "character_name" varchar,
  "teaser" text NOT NULL,
  "revealed_content" text NOT NULL,
  "media_url" varchar,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "discover_bookmarks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "post_id" integer NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "discover_comments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "post_id" integer NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "discover_likes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "post_id" integer NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "discover_post_hides" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "character_id" integer NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "discover_posts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "character_id" integer NOT NULL,
  "video_url" varchar NOT NULL,
  "thumbnail_url" varchar,
  "caption" text,
  "status" varchar NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "bookmark_count" integer DEFAULT 0,
  "share_count" integer DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "discover_shares" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "post_id" integer NOT NULL,
  "platform" varchar,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "feedbacks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "title" varchar,
  "content" text,
  "status" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "generation_quotas" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "character_id" integer NOT NULL,
  "gen_type" varchar NOT NULL,
  "count" integer,
  "updated_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "kol_applications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "platform" varchar,
  "platform_url" varchar,
  "follower_count" integer,
  "description" varchar,
  "status" varchar,
  "reviewed_at" timestamp without time zone,
  "reviewed_by" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "media_generation_tasks" (
  "id" varchar NOT NULL,
  "user_id" varchar NOT NULL,
  "character_id" integer NOT NULL,
  "character_name" varchar NOT NULL,
  "task_type" varchar NOT NULL,
  "status" varchar NOT NULL,
  "prompt" text NOT NULL,
  "final_prompt" text NOT NULL,
  "ref_image_url" varchar NOT NULL,
  "n" integer,
  "model" varchar,
  "model_level" varchar,
  "resolution" varchar,
  "duration" integer,
  "result_url" varchar,
  "error" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "priority" integer DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "memberships" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "tier" varchar,
  "started_at" timestamp without time zone,
  "expires_at" timestamp without time zone,
  "created_at" timestamp without time zone DEFAULT now(),
  "status" varchar DEFAULT 'active'::character varying,
  "cancelled_at" timestamp without time zone,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mood_entries" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "date" varchar NOT NULL,
  "mood" varchar NOT NULL,
  "note" text,
  "source" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "official_notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "target_user_id" varchar,
  "title" varchar NOT NULL,
  "body" text NOT NULL,
  "unread" integer,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "payment_checkouts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "plan_id" varchar NOT NULL,
  "provider" varchar NOT NULL,
  "status" varchar NOT NULL,
  "checkout_url" varchar,
  "instructions" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "crypto_order_no" varchar,
  "crypto_trade_no" varchar,
  "crypto_chain" varchar,
  "crypto_token" varchar,
  "crypto_amount" numeric(18,6),
  "crypto_checkout_url" varchar,
  "crypto_confirmed_at" timestamp with time zone,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "point_ledger" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "delta" integer NOT NULL,
  "reason" varchar NOT NULL,
  "reference_id" varchar,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "prompt_templates" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar NOT NULL,
  "model_pattern" varchar NOT NULL,
  "template_content" text NOT NULL,
  "variables_desc" json,
  "is_active" boolean NOT NULL,
  "priority" integer NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "referral_rewards" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "from_user_id" varchar,
  "level" integer,
  "points" integer,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "scene_posters" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "character_id" integer NOT NULL,
  "url" varchar NOT NULL,
  "description" text,
  "order" integer,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "script_scenes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "character_id" integer NOT NULL,
  "scene_key" varchar NOT NULL,
  "scene_name" varchar NOT NULL,
  "scene_description" text,
  "trigger_keywords" json,
  "emotional_tone" varchar,
  "media_type" varchar NOT NULL,
  "url" varchar NOT NULL,
  "description" text,
  "order" integer,
  "dialogue_script" text,
  "male_dialogue" text,
  "is_opening" integer,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "swap_results" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "task_id" integer NOT NULL,
  "file_path" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "swap_tasks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "face_image" text NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "system_config" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "key" varchar NOT NULL,
  "value" text NOT NULL,
  "description" text,
  "updated_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "trial_passes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "trial_type" varchar NOT NULL,
  "activated_at" timestamp without time zone,
  "expires_at" timestamp without time zone,
  "status" varchar,
  "purchase_reference_id" varchar,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_ad_clicks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "clicked_at" timestamp with time zone DEFAULT now(),
  "verified" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_character_chat_count" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "character_name" varchar NOT NULL,
  "chat_count" integer,
  "max_count" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_character_media" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "character_id" integer,
  "media_type" varchar,
  "media_url" varchar,
  "timestamp" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_favorites" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "post_id" integer NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_feedbacks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "category" varchar NOT NULL,
  "title" varchar NOT NULL,
  "content" varchar NOT NULL,
  "status" varchar,
  "admin_reply" varchar,
  "created_at" timestamp without time zone DEFAULT now(),
  "updated_at" timestamp without time zone DEFAULT now(),
  "attachments" json,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_intimacy" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "character_id" integer NOT NULL,
  "score" integer,
  "updated_at" timestamp without time zone,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_point_accounts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "balance" integer,
  "streak_days" integer,
  "last_checkin_date" varchar,
  "updated_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_referrals" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar,
  "referrer_id" varchar,
  "referral_code" varchar,
  "level" integer,
  "created_at" timestamp without time zone DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_roles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "email" varchar,
  "role" varchar NOT NULL,
  "created_at" timestamp without time zone,
  "updated_at" timestamp without time zone,
  "is_deactivated" boolean DEFAULT false,
  "deactivated_at" timestamp without time zone,
  "deactivated_by" varchar,
  "is_banned" boolean DEFAULT false,
  "banned_until" timestamp without time zone,
  "ban_reason" varchar,
  "banned_by" varchar,
  "banned_at" timestamp without time zone,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_scene_progress" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "user_id" varchar NOT NULL,
  "character_name" varchar NOT NULL,
  "current_scene_key" varchar,
  "current_scene_order" integer,
  "last_media_url" varchar,
  "last_media_sent_at" timestamp with time zone,
  "updated_at" timestamp with time zone DEFAULT now(),
  PRIMARY KEY ("id")
);
